[package]
name = "ec-gpu-gen"
version = "0.1.0"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
edition = "2018"
description = "Code generator for field and eliptic curve operations on the GPUs"
homepage = "https://github.com/filecoin-project/ff-cl-gen"
repository = "https://github.com/filecoin-project/ff-cl-gen"
license = "MIT/Apache-2.0"

[dependencies]
ec-gpu = { path = "../ec-gpu", git = "https://github.com/filecoin-project/ec-gpu", branch = "master" }

[dev-dependencies]
ff = "0.11.0"
blstrs = { git = "https://github.com/filecoin-project/blstrs", branch = "master", features = ["gpu"] }
rust-gpu-tools = { git = "https://github.com/filecoin-project/rust-gpu-tools", branch = "master", default-features = false }
rand = "0.8"
lazy_static = "1.2"
tempfile = "3.2.0"

[features]
default = ["opencl", "cuda"]
cuda = ["rust-gpu-tools/cuda"]
opencl = ["rust-gpu-tools/opencl"]
